### ISSUE TITLE
NEI Doesn't get CCC when loaded as a dependency of Chargepads

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#11]
At least that's what I presume this error means.

```
2013-04-13 23:30:49 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: codechicken/core/asm/CodeChickenCorePlugin
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:192)
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:147)
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:45)
2013-04-13 23:30:49 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1354)
2013-04-13 23:30:49 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: codechicken/core/asm/CodeChickenCorePlugin
2013-04-13 23:30:49 [INFO] [STDERR]     at codechicken.nei.asm.NEICorePlugin.getASMTransformerClass(NEICorePlugin.java:24)
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:267)
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
2013-04-13 23:30:49 [INFO] [STDERR]     ... 3 more
2013-04-13 23:30:49 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: codechicken.core.asm.CodeChickenCorePlugin
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
2013-04-13 23:30:49 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-13 23:30:49 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-13 23:30:49 [INFO] [STDERR]     ... 6 more
2013-04-13 23:30:49 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-04-13 23:30:49 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:227)
2013-04-13 23:30:49 [INFO] [STDERR]     ... 8 more
```

**allmods**
- `chargepads-1.5.1-universal-2.6.0.74.jar` http://smarturl.it/ChargePadsDEV
- `CodeChickenCore 0.8.5.6.jar`
- `NotEnoughItems 1.5.2.9.jar`

**Comment by agaricusb** [comment]
hm, NEI does have the CodeChickenCore dependency in mcmod.info, wonder why its not being picked up..
