### ISSUE TITLE
OpenCCSensors error

### ISSUE THREAD

**Issue by fogger** [agaricusb/ModAnalyzer#8]
Maybe the mention of modanalyzer is coincidental?

```
java.lang.NullPointerException
    at openccsensors.common.item.ItemSensorCard.func_77667_c(ItemSensorCard.java:45)
    at net.minecraft.item.Item.func_77657_g(Item.java:463)
    at agaricus.mods.modanalyzer.ModAnalyzer.dumpItems(ModAnalyzer.java:173)
    at agaricus.mods.modanalyzer.ModAnalyzer.tickEnd(ModAnalyzer.java:67)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:468)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**allmods**
`OpenCCSensors-0.1.5c.jar`
`ComputerCraft1.52.zip`

**Comment by agaricusb** [comment]
NPE at https://github.com/Cloudhunter/OpenCCSensors/blob/master/src/openccsensors/common/item/ItemSensorCard.java#L45

```
public String getUnlocalizedName(ItemStack itemStack)
{
    return String.format("item.openccsensors.%s", getSensorCard(itemStack).getSensor().getName());
}
```

I'll need catch this exception..
